# Generated by Django 5.0.7 on 2024-07-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_accountemail_resetpassword_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='images',
            field=models.ImageField(null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images/'),
        ),
    ]
