# Generated by Django 5.0.7 on 2024-07-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_course_images_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
