# Generated by Django 5.0.7 on 2024-07-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_remove_course_images_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='images',
            field=models.ImageField(null=True, upload_to='course_images/'),
        ),
    ]
