# Generated by Django 5.0.7 on 2024-07-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_course_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='images',
        ),
    ]
