# Generated by Django 5.0.7 on 2024-07-30 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_course_exercises_course_lessons_course_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='course',
            name='skills',
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('lessons', models.PositiveIntegerField(default=0)),
                ('exercises', models.PositiveIntegerField(default=0)),
                ('skills', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.course')),
            ],
        ),
    ]
