# Generated by Django 5.0.7 on 2024-07-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_remove_course_exercises_remove_course_lessons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='course',
        ),
    ]
