# Generated by Django 5.0.7 on 2024-07-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_remove_coursedetails_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseDetails',
        ),
        migrations.AddField(
            model_name='course',
            name='exercises',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
